apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-graphql-portal
  namespace: go-api-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-graphql-portal
  template:
    metadata:
      labels:
        app: go-graphql-portal
    spec:
      containers:
        - name: go-graphql-portal
          image: lokinious/go-graphql-portal:latest  # Replace with your actual Docker image details
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-graphql-portal-service
  namespace: go-api-practice
spec:
  selector:
    app: go-graphql-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
